INSERT INTO MOVIE (TITLE, IMAGE_NAME, GENRE, PRICE, DESCRIPTION, MOVIE_LENGTH) VALUES ('Avatar', 'avatar.jpg', 'Science Fiction', 159, 'En före detta marinkårssoldat blir förälskad i en blåhyad krigare på en främmande planet. Han ställer sig på hennes folks sida i deras kamp mot människans övergrepp på deras frodiga planet', '3 tim 12 min')
INSERT INTO MOVIE (TITLE, IMAGE_NAME, GENRE, PRICE, DESCRIPTION, MOVIE_LENGTH) VALUES ('Bamse Och Vulkanön', 'bamse.jpg', 'Barn', 109, 'Just som allt verkar vara lugnt och skönt hemma hos Bamse och hans vänner kommer ett nödanrop från Skalmans gamla forskarkollega, biologen Beanka, som mystiskt verkar ha försvunnit på en forskningsresa.', '1 tim 9 min')
INSERT INTO MOVIE (TITLE, IMAGE_NAME, GENRE, PRICE, DESCRIPTION, MOVIE_LENGTH) VALUES ('Black Adam', 'blackadam.jpg', 'Action', 109, 'Nära 5000 år efter att han tilldelats de forntida gudarnas allsmäktiga krafter - och fängslats lika snabbt - blir Black Adam befriad, redo att släppa lös sin egen form av rättvisa i den moderna världen.', '2 tim 4 min')
INSERT INTO MOVIE (TITLE, IMAGE_NAME, GENRE, PRICE, DESCRIPTION, MOVIE_LENGTH) VALUES ('Black Panther: Wakanda Forever', 'blackpanther.jpg', 'Action', 159, 'Wakandas invånare försöker gå vidare och tar hjälp av War Dog Nakia och Everett Ross, för att hitta en ny väg för kungariket Wakanda. Vi får också möta Namor, kungen av en dold undervattensnation.', '2 tim 41 min')

INSERT INTO SNACK (NAME, IMAGE_NAME, PRICE, DESCRIPTION) VALUES ('Djungelvrål', 'djungelvrål.jpg', 15.99, 'Vrålsalta lakritsdjur har varit en av Malacos favorit hos många godisälskare. Passar dig som älskar extra salt salmiak.')
INSERT INTO SNACK (NAME, IMAGE_NAME, PRICE, DESCRIPTION) VALUES ('Popcorn', 'popcorn.jpg', 29.99, 'Våra popcorn är gjorda på en majssort som kallas för Butterfly. Popcornmajset har fått sitt namn efter hur de ser ut när de är poppade.')
INSERT INTO SNACK (NAME, IMAGE_NAME, PRICE, DESCRIPTION) VALUES ('Chips', 'chips.jpg', 19.99, 'Saltade Potatischips är släta chips med lätt och härlig sälta som lyfter den goda potatisen till skyarna. De klassiska tunna chipsen är extra krispiga samtidigt som de nästan smälter i munnen.')

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Robert', 'Broberg', 'robert.broberg@gmail.com')

INSERT INTO PURCHASE (CUSTOMER_ID, MOVIE_ID) VALUES (1, 4)